version: '3'

services:
  mds-api:
    container_name: optimPerf
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - URL=mongodb://mongo1:30001,mongo2:30002,mongo3:30003/test?replicaSet=my-mongo-set
    networks:
      - mongo-cluster
    depends_on:
      - mongo1
    ports:
      - 3000:3000

  mongo1:
    container_name: mongo1
    image: mongo
    working_dir: /mongo
    volumes:
      - ./log/mongo1:/mongo
      - ./init.sh:/docker/database/init.sh
    command: bash -c "/docker/database/init.sh"
    ports:
      - 30001:30001
    networks:
      - mongo-cluster
    depends_on:
      - mongo2
      - mongo3

  mongo2:
    container_name: mongo2
    image: mongo
    working_dir: /mongo
    command: "mongod --port 30002 --replSet my-mongo-set --bind_ip_all --logpath mongo.log"
    volumes:
      - ./log/mongo2:/mongo
    ports:
      - 30002:30002
    networks:
      - mongo-cluster

  mongo3:
    container_name: mongo3
    image: mongo
    working_dir: /mongo
    command: "mongod --port 30003 --replSet my-mongo-set --bind_ip_all --logpath mongo.log"
    volumes:
      - ./log/mongo3:/mongo
    ports:
      - 30003:30003
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
